# Vista Victoria By-Laws — Advanced RAG Pipeline

Adapted from the DeepLearning.ai *Advanced RAG* course (Lesson 1).  
**Document**: Vista Victoria Strata Plan 105121 registered by-laws  
**LLM**: Claude Haiku (Anthropic) — for both RAG answering and Ragas evaluation  
**Embeddings**: Local `BAAI/bge-small-en-v1.5` — no external API needed

---
### What we'll build
| Stage | Technique | Why it matters for by-laws |
|---|---|---|
| 1 | **Basic RAG** | Baseline — splits doc into fixed chunks, retrieves top-k by similarity |
| 2 | **Sentence Window** | Indexes individual sentences for precise retrieval, but expands each hit to a 3-sentence window before answering — great for dense legal text |
| 3 | **Auto-merging** | Hierarchical chunks (2048→512→128 tokens); if enough leaf chunks from the same parent are retrieved, merges up to the full section |

### How we evaluate — the Ragas triad
| Metric | Question it answers |
|---|---|
| **Faithfulness** | Is every claim in the answer actually supported by the retrieved text? |
| **Answer Relevancy** | Does the answer actually address the question asked? |
| **Context Precision** | Are the retrieved chunks genuinely about the question? |

All three scores are 0–1; higher is better. No ground-truth answers required.

## Setup

```bash
pip install -r requirements.txt
```

Create a `.env` file in this directory:
```
ANTHROPIC_API_KEY=sk-ant-...
```

In [5]:
import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())
assert os.getenv("ANTHROPIC_API_KEY"), "Set ANTHROPIC_API_KEY in a .env file"
print("API key loaded.")

API key loaded.

## 1. Load the By-Laws Document

In [6]:
from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["./bylaws_clean.txt"]
).load_data()

print(f"Loaded {len(documents)} document(s)")
print(f"Total characters: {sum(len(d.text) for d in documents):,}")
print("\n--- First 500 chars ---")
print(documents[0].text[:500])

Loaded 1 document(s)
Total characters: 155,576

--- First 500 chars ---
============================================================
PAGE 1
============================================================
Strata Plan 105121
Vista Victoria
312 Victoria Road
GLADESVILLE NSW 2111
Registered By-Laws

============================================================
PAGE 2
============================================================
Residual Document Version 05
Lodger Details
Lodger Code
502700U
Name
JANE CRITTENDEN LAWYER
Address
PO BOX 4623
SYDNEY 2001
Lodg

In [7]:
from llama_index.core import Document

# Merge into a single Document so chunking strategies span the whole text
document = Document(text="\n\n".join(d.text for d in documents))
print(f"Merged document: {len(document.text):,} chars")

Merged document: 155,576 chars

## 2. Basic RAG Pipeline

**How it works**
1. Split the by-laws into fixed-size chunks (~1024 tokens, 20-token overlap)
2. Embed each chunk locally with `BAAI/bge-small-en-v1.5` and store in a vector index
3. At query time: embed the question → find the top-k most similar chunks → send them to Claude → get an answer

**Limitation for legal text**: a single by-law clause often spans multiple sentences. A fixed chunk boundary may cut the clause in half, losing key context.

In [8]:
from llama_index.llms.anthropic import Anthropic
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

llm = Anthropic(model="claude-haiku-4-5-20251001", temperature=0.1)
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

Settings.llm = llm
Settings.embed_model = embed_model

print("LLM and embedding model ready.")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

LLM and embedding model ready.

In [9]:
from llama_index.core import VectorStoreIndex

basic_index = VectorStoreIndex.from_documents([document])
basic_engine = basic_index.as_query_engine()
print("Basic vector index built.")

Basic vector index built.

In [10]:
response = basic_engine.query("What are the rules about keeping pets in the building?")
print(str(response))

# Rules About Keeping Pets in the Building

## Permitted Animals

You may keep:
- Goldfish or similar fish in an indoor aquarium
- A guide dog if you are visually or hearing impaired

For any other types or numbers of animals, you must obtain consent from the executive committee.

## Restrictions on Dogs

The executive committee will not consent to keeping:
- Large size dogs (except in exceptional circumstances with prescribed conditions)
- Dogs that are vicious, aggressive, noisy, or difficult to control
- Dogs that are not registered under the Companion Animals Act 1998 (NSW)
- Dangerous dogs under the Companion Animals Act 1998 (NSW)

## Control Requirements

- Your animal must not wander onto another lot or common property
- When taking your animal onto common property (such as for transport in and out of the building), you must restrain it by leash or pet cage and control it at all times

## Conditions and Responsibilities

- The executive committee may impose conditions when giving consent to keep an animal
- You are responsible for any noise your animal makes that causes unreasonable disturbance
- You are liable for any damage, loss of property, or injury caused by your animal
- You must clean up after your animal in both your lot and common property

## Removal Orders

The Building Manager can order you to remove your animal if it becomes offensive, vicious, aggressive, noisy, or a nuisance; if you breach consent conditions; or if you lack necessary consent.

In [11]:
response = basic_engine.query("Do I need approval from the owners corporation to renovate my apartment?")
print(str(response))

Whether you need approval from the Owners Corporation to renovate your apartment depends on the scope of your renovation work.

If your renovation involves work that is confined to the interior of your lot and does not affect Common Property, you generally would not need approval. However, if your renovation involves any of the following, you must first obtain approval from the Owners Corporation:

- Leaving anything on Common Property
- Obstructing the use of Common Property
- Using any part of Common Property for your own purposes
- Erecting any structure on Common Property
- Attaching any item to Common Property
- Doing anything that might cause damage to Common Property
- Altering Common Property

Additionally, if your renovation involves building works or alterations, specific provisions apply that may require approval.

If your renovation includes installing fixtures that serve your lot (such as built-in appliances or structural elements), you are responsible for maintaining them in good repair and ensuring any visible external work is consistent with the appearance of the rest of the building.

It is advisable to contact the Strata Manager in writing with details of your planned renovation to determine whether Owners Corporation approval is required for your specific project.

In [12]:
response = basic_engine.query("What noise restrictions apply and during what hours?")
print(str(response))

Based on the provided context, there are no specific noise restrictions mentioned with designated hours.

The context does address noise transmission related to floor coverings. It requires that floor space and surrounding areas within a Lot be covered or treated to reduce appropriately and suitably noise transmission that might unreasonably disturb another Owner or Occupier. Additionally, when installing certain floor surfaces and approved insulation (other than carpet with approved underlay), acoustic consultants must verify that the installation satisfies requirements related to noise transmission.

However, the context does not specify particular times of day during which noise restrictions apply or provide decibel limits or other quantifiable noise standards with time-based restrictions.

## 3. Evaluation with Ragas

### How Ragas evaluation works

For each question we collect three things from the query engine:
- **question** — the input
- **answer** — Claude's response
- **contexts** — the actual chunks that were retrieved and fed to Claude (`response.source_nodes`)

Ragas then uses Claude Haiku *as the judge* to score each (question, answer, contexts) triple.  
Everything runs on the same `ANTHROPIC_API_KEY` — no other keys needed.

```
query_engine.query(q)
      │
      ├─ answer      ──► Ragas judges: does the answer address the question?
      │                                                 → answer_relevancy
      │
      └─ source_nodes ─► Ragas judges: are these chunks on-topic?    → context_precision
                         Ragas judges: does the answer stay within    → faithfulness
                                       what the chunks actually say?
```

In [13]:
# Questions a Vista Victoria owner would realistically ask
eval_questions = [
    "What are the rules about keeping pets in the building?",
    "What noise restrictions apply and during what hours?",
    "Do I need approval to make renovations or alterations to my lot?"
    # "What are the parking rules for owners and visitors?",
    # "Who is responsible for maintaining common property?",
    # "Can I put up a satellite dish or air-conditioning unit on the outside of my apartment?",
    # "What are the rules about rubbish and waste disposal?",
    # "Am I allowed to run a business from my apartment?",
]

for i, q in enumerate(eval_questions, 1):
    print(f"{i}. {q}")

1. What are the rules about keeping pets in the building?
2. What noise restrictions apply and during what hours?
3. Do I need approval to make renovations or alterations to my lot?

### 3a. Evaluate the Basic RAG Pipeline

In [14]:
from utils import evaluate_pipeline

basic_df = evaluate_pipeline(basic_engine, eval_questions)
print("=== Basic RAG — aggregate scores ===")
print(basic_df[["faithfulness", "answer_relevancy"]].mean().round(3))

=== Basic RAG — aggregate scores ===
faithfulness        0.933
answer_relevancy    0.767
dtype: float64

In [26]:
# Per-question breakdown
basic_df[["question", "faithfulness", "answer_relevancy"]]

,question,faithfulness,answer_relevancy
0,What are the rules about keeping pets in the b...,0.95,0.95
1,What noise restrictions apply and during what ...,0.90,0.40
2,Do I need approval to make renovations or alte...,0.95,0.95

## 4. Advanced RAG — Sentence Window Retrieval

**How it works**
1. Each *sentence* gets its own index node → embedding captures a precise meaning unit
2. Each node also stores a `window` of the 3 surrounding sentences as metadata
3. At query time: retrieve the most relevant sentences, then **replace each hit with its window** before passing to Claude

**Why this helps for by-laws**: a clause like *"Owners must not allow their pet to enter the pool area"* is one sentence — indexing it alone gives precise retrieval. But Claude needs the surrounding context (what pets are allowed, what the pool area rules are) to give a complete answer. The window provides that without bloating the index.

In [16]:
from utils import build_sentence_window_index, get_sentence_window_query_engine

sentence_index = build_sentence_window_index(
    document, llm, embed_model, save_dir="sentence_index"
)
sw_engine = get_sentence_window_query_engine(sentence_index)
print("Sentence-window index built.")

Sentence-window index built.

In [17]:
response = sw_engine.query("What are the rules about keeping pets in the building?")
print(str(response))

# Rules About Keeping Pets

## Permitted Animals

You may keep:
- Goldfish or similar fish in an indoor aquarium
- A guide dog if you are visually or hearing impaired

For any other types or numbers of animals, you must obtain consent from the executive committee.

## Restrictions on Dogs

The executive committee will not approve consent to keep:
- Large size dogs (except in exceptional circumstances with prescribed conditions)
- Dogs that are vicious, aggressive, noisy, or difficult to control
- Dogs that are not registered under the Companion Animals Act 1998 (NSW)
- Dangerous dogs under the Companion Animals Act 1998 (NSW)

## Controlling Your Animal

- Your animal must not wander onto another resident's lot or common property
- When transporting your animal through common property, you must restrain it (by leash or pet cage) and control it at all times

## Conditions and Responsibilities

- The executive committee may impose conditions when granting consent to keep an animal
- You are responsible for any noise your animal makes that causes unreasonable disturbance
- You are liable for any damage, loss of property, or injury caused by your animal
- You must clean up after your animal in both your lot and common property

## Removal of Animals

The Building Manager can order you to remove your animal if it becomes offensive, vicious, aggressive, noisy, or a nuisance; if you breach consent conditions; or if you lack necessary consent.

In [18]:
response = sw_engine.query("What noise restrictions apply and during what hours?")
print(str(response))

# Noise Restrictions

Based on the by-laws provided, there are noise restrictions related to floor coverings and installations in residential lots.

## Floor Covering Noise Requirements

You must ensure that all floor space and surrounding areas within your lot are covered or treated to reduce appropriately and suitably noise transmission that might unreasonably disturb another owner or occupier. This applies particularly when:

- Installing a floor surface and approved insulation (other than carpet with approved underlay)
- Removing or interfering with floor coverings or treatments

The by-laws require that floor installations meet a minimum sound proof rating as determined by the Owners Corporation's guidelines, and may require verification by qualified acoustic consultants.

## Important Note on Ongoing Obligations

Meeting the prescribed acoustic standards does not excuse you from an ongoing obligation to reduce appropriately and suitably noise transmission that might unreasonably disturb another owner or occupier at any time.

## Specific Hours

**The context provided does not specify particular hours during which noise restrictions apply.** The restrictions appear to be general ongoing obligations rather than time-specific restrictions.

### 4a. Evaluate the Sentence Window Pipeline

In [19]:
sw_df = evaluate_pipeline(sw_engine, eval_questions)
print("=== Sentence Window — aggregate scores ===")
print(sw_df[["faithfulness", "answer_relevancy"]].mean().round(3))

=== Sentence Window — aggregate scores ===
faithfulness        0.917
answer_relevancy    0.700
dtype: float64

In [20]:
sw_df[["question", "faithfulness", "answer_relevancy"]]

,question,faithfulness,answer_relevancy
0,What are the rules about keeping pets in the b...,0.95,0.95
1,What noise restrictions apply and during what ...,0.85,0.20
2,Do I need approval to make renovations or alte...,0.95,0.95

## 5. Advanced RAG — Auto-merging Retrieval

**How it works**
1. The document is split into a *hierarchy*: 2048-token parents → 512-token children → 128-token leaf chunks
2. Only the **leaf** (128-token) chunks are stored in the vector index — small enough for precise embedding
3. At query time: retrieve the most relevant leaves. If enough sibling leaves from the same 512-token parent are hit, **merge up** to the parent. Check again at the 2048 level.
4. Result: scattered retrievals automatically merge back into coherent by-law sections

**Why this helps for by-laws**: By-law 8 (Building Works) spans several pages with many sub-clauses. If your question about renovations triggers multiple sub-clause matches, auto-merging pulls the whole section rather than disconnected fragments.

In [21]:
from utils import build_automerging_index, get_automerging_query_engine

automerging_index = build_automerging_index(
    documents, llm, embed_model, save_dir="merging_index"
)
am_engine = get_automerging_query_engine(automerging_index)
print("Auto-merging index built.")

Auto-merging index built.

In [22]:
response = am_engine.query("What approval do I need to make alterations to my lot?")
print(str(response))

# Approvals Required for Alterations to Your Lot

The approval requirements depend on the type of alteration you're planning:

## Fire Doors
If you want to replace or make alterations to a fire door that gives access to your Lot, you must obtain **written approval from the Owners Corporation** before proceeding. Any alterations must also comply with fire regulations under the Building Code of Australia.

## Floor Coverings
If you plan to remove or interfere with floor coverings or treatments in your Lot, or install a floor surface with approved insulation other than carpet with approved underlay, you must obtain **written consent** before doing so.

## General Renovations
For renovations to your Lot that don't involve permanent changes to Common Property but are likely to inconvenience other Owners or Occupiers during the work, specific procedures apply under the renovation by-laws.

## Maintenance and Repairs
For installations or alterations that service your Lot (whether you made them or not), you're responsible for properly maintaining, repairing, and replacing them as necessary.

Additionally, if you change the existing use of your Lot in a way that may affect insurance premiums, you must notify the Building Manager.

In [23]:
response = am_engine.query("What are the rules about keeping pets in the building?")
print(str(response))

> Merging 4 nodes into parent node.
> Parent node id: 0b7fcf2c-f023-4297-8a8c-1e290401eb9d.
> Parent node text: 13.3
The executive committee will not give you consent to keep any:
(a)
large size dog except ...

# Rules About Keeping Pets in the Building

## Permitted Animals

You may keep:
- Goldfish or other similar fish in an indoor aquarium
- A guide dog if you are visually or hearing impaired

## Consent Requirements

For any other types or numbers of animals, you must obtain consent from the executive committee.

## Restrictions on Dogs

The executive committee will not consent to keeping:
- Large size dogs (except in exceptional circumstances with prescribed conditions)
- Dogs that are vicious, aggressive, noisy, or difficult to control
- Dogs not registered under the Companion Animals Act 1998 (NSW)
- Dangerous dogs under the Companion Animals Act 1998 (NSW)

## Control and Containment

- Your animal must not wander onto another lot or common property
- When taking your animal onto common property, you must restrain it (by leash or pet cage) and control it at all times

## Responsibilities

You are responsible for:
- Any noise your animal makes that causes unreasonable disturbance
- Any damage, loss of property, or injury caused by your animal
- Cleaning up after your animal in both your lot and common property

## Enforcement

The Building Manager may order you to remove your animal if it becomes offensive, vicious, aggressive, noisy, or a nuisance; if you breach consent conditions; or if you lack necessary consent.

Visitors are not permitted to bring animals into the building unless they are guide dogs or hearing dogs and the visitor is visually or hearing impaired.

### 5a. Evaluate the Auto-merging Pipeline

In [25]:
am_df = evaluate_pipeline(am_engine, eval_questions)
print("=== Auto-merging — aggregate scores ===")
print(am_df[["faithfulness", "answer_relevancy"]].mean().round(3))

> Merging 4 nodes into parent node.
> Parent node id: 0b7fcf2c-f023-4297-8a8c-1e290401eb9d.
> Parent node text: 13.3
The executive committee will not give you consent to keep any:
(a)
large size dog except ...

=== Auto-merging — aggregate scores ===
faithfulness        0.917
answer_relevancy    0.917
dtype: float64

In [ ]:
am_df[["question", "faithfulness", "answer_relevancy"]]

## 6. Side-by-side Comparison

In [ ]:
import pandas as pd

metrics = ["faithfulness", "answer_relevancy"]

comparison = pd.DataFrame(
    {
        "Basic RAG":       basic_df[metrics].mean(),
        "Sentence Window": sw_df[metrics].mean(),
        "Auto-merging":    am_df[metrics].mean(),
    }
).round(3)

print(comparison.to_string())
print("
Best per metric:")
print(comparison.idxmax(axis=1))

In [ ]:
# Per-question faithfulness comparison — useful for spotting which questions
# expose retrieval failures in each approach
faith_compare = pd.DataFrame({
    "question":        basic_df["question"],
    "basic":           basic_df["faithfulness"].round(3),
    "sentence_window": sw_df["faithfulness"].round(3),
    "auto_merging":    am_df["faithfulness"].round(3),
})
faith_compare

## Tips & Next Steps

### Reading Ragas scores (0–1)
| Score | Meaning |
|---|---|
| > 0.8 | Good |
| 0.5–0.8 | Moderate — worth investigating |
| < 0.5 | Poor — retrieval or generation problem |

### Common failure modes in legal text
- **Low context precision** → chunks are on a nearby topic but not the exact by-law  
  → Try increasing `similarity_top_k` and letting the reranker filter harder
- **Low faithfulness** → Claude is adding interpretation beyond the retrieved text  
  → Tighten the prompt (see custom prompt below)
- **Low answer relevancy** → the question is too vague; the retriever finds related but off-topic chunks  
  → Be more specific, e.g. *"By-law 12 — what does it say about noise?"*

### Switching to a more capable model for complex questions
```python
# Haiku — fast and cheap for exploration
llm = Anthropic(model="claude-haiku-4-5-20251001", temperature=0.1)

# Sonnet — better reasoning for multi-clause legal questions
llm = Anthropic(model="claude-sonnet-4-6", temperature=0.1)
```

### Adding a custom system prompt to reduce hallucination
```python
from llama_index.core import PromptTemplate

qa_prompt = PromptTemplate(
    "You are a strata by-law assistant for Vista Victoria (SP105121), Gladesville NSW.\n"
    "Answer only from the context below. Cite the by-law number where applicable.\n"
    "If the context does not cover the question, say so explicitly — do not guess.\n\n"
    "Context:\n{context_str}\n\n"
    "Question: {query_str}\n"
    "Answer:"
)
basic_engine.update_prompts({"response_synthesizer:text_qa_template": qa_prompt})
```

In [27]:
q = "What are the rules about keeping pets?"
print("BASIC:"); print(basic_engine.query(q))
print("SENTENCE WINDOW:"); print(sw_engine.query(q))
print("AUTO-MERGING:"); print(am_engine.query(q))

BASIC:
# Rules About Keeping Pets

**Permitted Animals:**
You may keep goldfish or other similar fish in an indoor aquarium, or a guide dog if you are visually or hearing impaired. For any other types or numbers of animals, you must obtain consent from the executive committee.

**Restrictions on Dogs:**
The executive committee will not consent to keeping:
- Large size dogs (except in exceptional circumstances with prescribed conditions)
- Dogs that are vicious, aggressive, noisy, or difficult to control
- Dogs that are not registered under the Companion Animals Act 1998 (NSW)
- Dangerous dogs under the Companion Animals Act 1998 (NSW)

**Controlling Your Animal:**
- Your animal must not wander onto another lot or common property
- When taking your animal onto common property (such as transporting it in and out of the building), you must restrain it by leash or pet cage and control it at all times

**Conditions and Responsibilities:**
- The executive committee may impose conditions on pet ownership
- You are responsible for any noise your animal makes that causes unreasonable disturbance
- You are liable for any damage, loss of property, or injury caused by your animal
- You must clean up after your animal in both your lot and common property

**Removal of Animals:**
The Building Manager can order you to remove your animal if it becomes offensive, vicious, aggressive, noisy, or a nuisance; if you breach consent conditions; or if you lack the necessary consent to keep it.
SENTENCE WINDOW:
# Rules About Keeping Pets

## Permitted Animals

You may keep:
- Goldfish or other similar fish in an indoor aquarium
- A guide dog if you are visually or hearing impaired

For any other types or numbers of animals, you must obtain consent from the executive committee.

## Restrictions on Dogs

The executive committee will not consent to keeping:
- Large size dogs (except in exceptional circumstances with prescribed conditions)
- Dogs that are vicious, aggressive, noisy, or difficult to control
- Dogs that are not registered under the Companion Animals Act 1998 (NSW)
- Dangerous dogs under the Companion Animals Act 1998 (NSW)

## Controlling Your Animal

- Your animal must not wander onto another lot or common property
- When taking your animal onto common property (such as for transport in and out of the building), you must restrain it by leash or pet cage and control it at all times

## Conditions and Responsibilities

- The executive committee may impose conditions when granting consent to keep an animal
- You are responsible for any noise your animal makes that causes unreasonable disturbance
- You are liable for any damage to property or injury to persons caused by your animal
- You must clean up after your animal in both your lot and common property
- The Building Manager can order removal of your animal if it becomes offensive, vicious, aggressive, noisy, or a nuisance, or if you breach consent conditions

## Guests' Animals

You must not allow your guests to bring animals into the building unless they are guide dogs or hearing dogs and the guests are visually or hearing impaired.
AUTO-MERGING:
> Merging 4 nodes into parent node.
> Parent node id: 0b7fcf2c-f023-4297-8a8c-1e290401eb9d.
> Parent node text: 13.3
The executive committee will not give you consent to keep any:
(a)
large size dog except ...

# Rules About Keeping Pets

## Permitted Animals

You may keep:
- Goldfish or other similar fish in an indoor aquarium
- A guide dog if you are visually or hearing impaired

For any other types or numbers of animals, you must obtain consent from the executive committee.

## Restrictions on Dogs

The executive committee will not consent to keeping:
- Large size dogs (except in exceptional circumstances with prescribed conditions)
- Dogs that are vicious, aggressive, noisy, or difficult to control
- Dogs that are not registered under the Companion Animals Act 1998 (NSW)
- Dangerous dogs under the Companion Animals Act 1998 (NSW)

## Animal Control Requirements

If you keep an animal, you must:
- Ensure it does not wander onto another lot or common property
- Restrain and control it at all times when on common property (using a leash or pet cage)
- Comply with any conditions set by the executive committee

## Liability and Responsibilities

You are responsible for:
- Any unreasonable disturbance caused by noise from your animal
- Any damage, loss of property, or injury caused by your animal
- Cleaning up after your animal in both your lot and common property

## Removal of Animals

The Building Manager may order you to remove your animal if it becomes offensive, vicious, aggressive, noisy, or a nuisance; if you breach consent conditions; or if you lack necessary consent.

In [28]:
response = sw_engine.query("What are the noise rules?")
print(str(response))
print("\n--- Retrieved chunks ---")
for i, node in enumerate(response.source_nodes, 1):
    print(f"\nChunk {i}:")
    print(node.text)

# Noise Rules

The noise rules primarily relate to floor coverings and installations:

## Floor Installation Noise Requirements

When installing floor surfaces and approved insulation (other than carpet with approved underlay), you must:

- Treat all floor space and surrounding areas within your lot to reduce noise transmission that might unreasonably disturb other owners or occupiers
- Comply with guidelines that may specify a minimum sound proof rating that the floor surface and surrounding areas must attain
- Engage qualified acoustic consultants to carry out acoustic services for non-carpet floor installations
- Provide confirmation within 14 days of installation, which may include a written report from a qualified acoustic consultant guaranteeing that the installation satisfies noise-related requirements

## Ongoing Obligation

Even if your installation meets the prescribed acoustic standards, you remain under an ongoing obligation to reduce noise transmission appropriately and suitably to avoid unreasonably disturbing other owners or occupiers.

## Renovation Work

When carrying out renovations, you must comply with work methods and arrangements that the executive committee deems necessary, which may include provisions related to noise management during construction activities.

--- Retrieved chunks ---

Chunk 1:
Window coverings
5.3
Window coverings (e.g. curtains, blinds) in your Lot must have a white backing
and otherwise be of a colour and design approved by the Owners Corporation
as in keeping with the design and appearance of Vista Victoria Gladesville
when viewed from outside.
6
Floor coverings in your Lot
6.1
The Owners Corporation may from to time issue guidelines under this by-law
in relation to the installation of a floor surface and Approved Underlay and
Approved Insulation in a Lot ("Guidelines"). The Guidelines form part of this
by-law and include the following:
Page 17 of 146

============================================================
PAGE 19
============================================================
(a)
the type or types of floor surfaces, Approved Underlay and Approved
Insulation that may be installed in a Lot;
(b)
the standard of floor surfaces and Approved Underlay and Approved
Insulation that may be installed in a Lot;
(c)
the method of installation of the floor surface, Approved Underlay and
Approved Insulation in a Lot, including treating surrounding areas to
reduce noise transmission that might unreasonably disturb another
Owner or Occupier;
(d)
that a firm or firms of qualified acoustic consultants is to carry out
acoustic services in relation to the installation of a floor surface and
Approved Insulation other than carpet and Approved Underlay in a Lot;
(e)
test or tests that the Owners Corporation requires you to carry out in
relation to the installation of a floor surface and Approved Insulation
other than carpet and Approved Underlay in a Lot;
(f)
the minimum sound proof rating that the floor surface and surrounding
areas must attain;
(g)
the ability for the Owners Corporation to independently verify your
compliance with this by-law;
(h)
the payment of a bond for an amount that the Owners Corporation
reasonably determines to ensure that you comply with this by- law; and
(i)
such other matters as the Owners Corporation reasonably determines
from time to time.
6.2
You must
(a)
comply with the Guidelines;
(b)
ensure that all floor space and surrounding areas within your Lot are
covered or otherwise treated in accordance with the Guidelines to
reduce appropriately and suitably noise transmission that might
Page 18 of 146

============================================================
PAGE 20
============================================================
unreasonably disturb another Owner or Occupier;
(c)
obtain written consent to remove or interfere with floor coverings or
treatments in your Lot or Install a floor surface and Approved Insulation
other than carpet with Approved Underlay; and
(d)
obtain a Checklist from the Building Manager before you commence
any work.
6.3
If you wish to change your floor surface, the executive committee may withhold
approval or give consent conditionally or unconditionally in their absolute
discretion. You must comply with all conditions even If that means you must
propose a Common Property Rights By-Law and wait until that by-law is passed
before you undertake floor covering work.
6.4
You may install carpet provided it has an underlay equal to Approved Underlay
without requiring specific consent. All other types of underlay and carpets
without underlay will require specific consent.
6.5
In requesting consent under this by-law, you must provide to the Building
Manager the following documentation:
(a)
the documentation set out in the Guidelines; and
(b)
such other material or documentation that the Building Manager acting
on behalf of the executive committee reasonably requires.
6,6
Within 14 days following the Installation of a floor surface and Approved
Insulation other than carpet and Approved Underlay in a Lot, you must provide
to the Building Manager such confirmation, certificate or report or as the
executive committee may require and which may include a written report from
a qualified acoustic consultant addressed to you and the Owners Corporation
that guarantees
(a)
the completed installation has been inspected by that acoustic
consultant; and
(b)
all matters in relation to the installation of the floor surface and
Page 19 of 146

============================================================
PAGE 21
============================================================
Approved Insulation satisfy this by-law, including the Guidelines.
6.7
Meeting a standard, whether acoustic or otherwise, prescribed in these by-laws
or in any Guidelines does not exonerate or excuse you from an ongoing
obligation to reduce appropriately and suitably nolse transmission that might
unreasonably disturb another Owner or Occupier.
6.8
Anything you do or should do under this by-law must be done atyour own cost.
6.9
You must accept liability for any damage caused to any part of your Lot, the
Common Property or any other Lot as a result of the removal or installation of
a floor surface, Approved Insulation carpeting and Approved Underlay to your
Lot and will be responsible to make good that damage Immediately after it
occurs.

Chunk 2:
30.9
You must comply with the Owners Corporation's reasonable instructions about
Security Keys.
31
Letting and Planning Compliance
31.1
In this by-law
"Long term sleeping accommodation" means accommodation provided to
the same person or persons for a period of more than 28 consecutive days, or
that Is the subject of an agreement for its provision to the same person or
Page 61 of 146

============================================================
PAGE 63
============================================================
persons for a period of more than 28 consecutive days.
"Maximum Number" means:
(a)
In the case of a Lot with 1 authorised bedroom; up to 2 adults at any
one time;
(b)
In the case of a Lot with 2 authorised bedrooms; up to 4 adults at any
one time; and
(c)
In the case of a Lot with 3 authorised bedrooms; up to 6 adults at any
one time.
31.2
The Owners Corporation Is concerned that unrestricted numbers of residents
in some Lots:
(a)
may place extra strain on common services, compromising fire safety
services designed and installed in the Building and posing a greater
security risk to the Building;
(b)
is in contravention of Regulation 22 of the Public Health (General)
Regulation 2002 (a copy of which is available on request to the Building
Manager); and
(c)
constitutes overcrowding which may void or nullify the Building's
insurance policies and the payout of certain Insurance claims.
31.3
The Common Property services in Vista Victoria Gladesville cannot
accommodate more persons than the configurations of the Lots Intended. The
Owners Corporation proposes this by-law In the interests of properly
discharging its duty to manage and control the use of the Common Property.
31.4
In addition to prohibitions and obligations imposed in other by-laws for Vista
Victoria Gladesville, you must not and must not permit any other person to:
(a)
allow, condone or suffer Long Term Sleeping Accommodation in your
Lot by more than the Maximum Number;
Page 62 of 146

============================================================
PAGE 64
============================================================
(b)
alter or Interfere with Common Property services, conduits, pipes and
cables in the Building; and
(c)
instali partitions within Lots in an attempt to create more rooms or
separate rooms to accommodate more than the Maximum Number
without the Owners Corporation's prior written consent (such consent
to be given or withheld In its reasonable discretion.)
31.5
You will be liable for any damage to the Common Property caused by your
breach of this by-law.
31.6
You must Indemnify the Owners Corporation against any claim, action, demand
or expense Incurred in relation to:
(a)
overcrowding in excess of the permitted Maximum Number in your Lot
in breach of this by-law; and
(b)
increased Insurance premiums as a result of a breach of this by- law;
(c)
the exercise of its rights under this by-law; and
(d)
enforcement of this by-law.
31.7
This by-law confers on the Owners Corporation the following additional
functions, powers, authorities and duties:
(a)
the power to prohibit you from permitting more than the Maximum
Number to reside in any Lot;
(b)
where you do not comply with this by-law (in the executive committee's
reasonable opinion), the authority to enter any part of Vista Victoria
Gladesville to carry out the necessary investigation to confirm that
opinion;
(c)
the power to engage in whatever legal action may be necessary or
desirable to stop the breach of this by-law; and
(d)
the authority to recover the costs of carrying out the activities referred
Page 63 of 146

============================================================
PAGE 65
============================================================
to in sub-clauses (b) and (c) of this clause from the respective Owner
as a debt, due and payable at the Owners Corporation's direction and
which, if unpald within 1 month of being due, will bear simple interest at
the rate of 10 percent per annum or, if the regulations provide for
another rate, that other rate, until paid and the interest will form part of
that debt.
32.
Tenancies
32.1
An Occupier must be a party to a current lease under the Residential Tenancies
Act 2010 (NSW), as amended, or where there are two or more Occupiers, at
least one of those Occupiers must be a party to such lease.

Chunk 3:
6.7
Meeting a standard, whether acoustic or otherwise, prescribed in these by-laws
or in any Guidelines does not exonerate or excuse you from an ongoing
obligation to reduce appropriately and suitably nolse transmission that might
unreasonably disturb another Owner or Occupier.
6.8
Anything you do or should do under this by-law must be done atyour own cost.
6.9
You must accept liability for any damage caused to any part of your Lot, the
Common Property or any other Lot as a result of the removal or installation of
a floor surface, Approved Insulation carpeting and Approved Underlay to your
Lot and will be responsible to make good that damage Immediately after it
occurs.
6.10
You must indemnify the Owners Corporation against any loss or damage the
Owners Corporation suffers as a result of the performance, maintenance or
replacement of your floor surface, Approved Insulation, carpeting and
Approved Underlay and will pay those amounts (including legal costs) to the
Owners Corporation upon request.
6.11
You must maintain repair and replace any flooring installed in your Lot or for
the benefit of your Lot pursuant to this by-law or a special privilege or Common
Property Rights By-Law, at your own expense.
7
Renovations to your Lot - General Procedure
7.1
This by-law applies if you are an Owner and want to do Renovations to your
Lot that:
(a)
do not involve permanent changes or additions to Common Property;
(b)
are likely to inconvenience other Owners or Occupiers when they are
being carried out (e.g. because of their scope, the duration of the works
period or other reasons); and
(c)
are not already approved in a separate Common Property Rights By-
Page 20 of 146

============================================================
PAGE 22
============================================================
Law applying to your Lot.
7.2
This by-law does not permit you to carry out Building Work; such works
Involving Common Property and being the subject of by-law 8.
7.3
If you wish to undertake Renovations you must not commence any such work
before you:
(a)
obtain a Checklist from the Building Manager;
(b)
obtain necessary consents from the Owners Corporation and all
relevant Government Agencies and supply evidence in writing to the
executive committee of all such Government Agencies' consents;
(c)
find out where service lines and pipes are located;
(d)
give the Building Manager 14 days' written notice describing in detail
what work is proposed;
(e)
where the executive committee deems it necessary, then before
commencing work, arrange with the Bullding Manager:
i.
a suitable time and means by which to access Vista Victoria
Gladesville;
ii.
work hours, work methods and disposal of debris;
ili.
a nominee who will be responsible for supervising the work and
be contactable in emergencies at all times; and
İv.
delivery of the Bond to the Building Manager.
7.4
When carrying out Renovations you must:
(a)
comply (and ensure that contractors and any persons involved in doing
the work comply) with those arrangements referred to in clause 7.3;
(b)
use qualified, reputable, licensed and insured contractors;
Page 21 of 146

============================================================
PAGE 23
============================================================
(c)
not damage service lines or pipes or interrupt services to Vista Victoria
Gladesville;
(d)
do the work in a proper manner and to the Owners Corporation's and
the relevant Government Agencies' reasonable satisfaction;
(e)
be liable for and immediately repair any damage caused to Common
Property, your Lot or another Lot or the property of any Occupier;
(f)
not damage or interfere with or alter the Integrity of fire rated doors or
walls; and
(g)
comply with all the other relevant by-laws.
7.5
After carrying out work approved under this by-law, and if reasonably requested
to do so by the Owners Corporation you must produce written certification that
the works meet relevant Australian Building, engineering, fire and/or acoustic
standards for such works and thatthe structural integrity of the Building has not
been compromised by your Renovations.
7.6
At all times, you must indemnify the Owners Corporation from all claims, loss
or damage the Owners Corporation suffers (including legal costs) as a result
of the performance, maintenance, repair or replacement of your Renovations.
7.7
Your Bond may be used by the Owners Corporation in its discretion to repair
any damage caused to Common Property by your Renovations or associated
activities.

In [29]:
nodes = list(basic_index.docstore.docs.values())
print(f"Total chunks: {len(nodes)}")
print(f"\n--- Chunk 0 ---")
print(nodes[0].text)
print(f"\n--- Chunk 1 ---")
print(nodes[1].text)

Total chunks: 40

--- Chunk 0 ---
============================================================
PAGE 1
============================================================
Strata Plan 105121
Vista Victoria
312 Victoria Road
GLADESVILLE NSW 2111
Registered By-Laws

============================================================
PAGE 2
============================================================
Residual Document Version 05
Lodger Details
Lodger Code
502700U
Name
JANE CRITTENDEN LAWYER
Address
PO BOX 4623
SYDNEY 2001
Lodger Box
1W
Email
JANE@JANECRITTENDENLAWYER.COM.AU
Reference
7297
Land Registry Document Identification
AV373804
STAMP DUTY:
Consolidation/Change of By-laws
Jurisdiction
NEW SOUTH WALES
Privacy Collection Statement
The information in this form is collected under statutory authority and used for the purpose of maintaining publicly searchable registers and
indexes.
Land Title Reference
CP/SP105121
N
Part Land Affected?
Land Description
Owners Corporation
THE OWNERS - STRATA PLAN NO. SP105121
Other legal entity
Meeting Date
05/08/2025
Amended by-law No.
Details
Added by-law No.
Details
Repealed by-law No.
Details
NOT APPLICABLE
SPECIAL BY-LAWS 1 and 2
NOT APPLICABLE
The subscriber requests the Registrar-General to make any necessary recording in the Register to give effect to this instrument, in respect of
the land or interest described above.
Attachment
See attached Conditions and Provisions
See attached Approved forms
See attached Approved forms
Execution
The Certifier has taken reasonable steps to verify the identity of the applicant or his, her or its administrator or attorney.
The Certifier holds a properly completed Client Authorisation for the Conveyancing Transaction including this Registry Instrument or
Document.
The Certifier has retained the evidence supporting this Registry Instrument or Document.
The Certifier has taken reasonable steps to ensure that this Registry Instrument or Document is correct and compliant with relevant legislation
and any Prescribed Requirement.
Executed on behalf of
THE OWNERS - STRATA PLAN NO. SP105121
Signer Name
JANE CRITTENDEN
Signer Organisation
JANE FRANCES CRITTENDEN
Signer Role
PRACTITIONER CERTIFIER
Execution Date
28/08/2025

============================================================
PAGE 3
============================================================
ANNEXURE "A"
VISTA VICTORIA GLADESVILLE BY-LAWS
STRATA PLAN NO. 105121
THESE BY-LAWS AFFECT EVERY OWNER, RESIDENT AND VISITOR TO VISTA
VICTORIA GLADESVILLE
THE PROVISIONS OF THIS INSTRUMENT INCORPORATE AND ARE SUBJECT
TO THE PROVISIONS IMPLIED BY CLAUSE 5, SCHEDULE 4 STRATA SCHEMES
DEVELOPMENT ACT 2015, EXCEPT TO THE EXTENT THIS INSTRUMENT
PROVIDES OTHERWISE.
1
Dictionary Meaning of words
1.1
This by-law explains words written Like This and some other words that have
special meanings. Words and expressions defined in the Act that this by-law
does not explain have the same meaning as they do in the Act.
1.2
In the by-laws:
Act is the Strata Schemes Management Act 2015 (NSW) as amended and/or
replaced from time to time.
Annexure A is the annexure to these by-laws containing a form of Consent
Form referred to in by-law no. 8 - Building Works.
approval means:
(a)
an approval or certificate as may be required by law (or under the terms
of an Approval) to be obtained from or provided by an authority;
(b)
a development consent or complying development certificate within the
meaning of the Environmental Planning and Assessment Act 1979;
(c)
a certificate within the meaning of Division 6.3 of the Environmental
Planning and Assessment Act 1979;
(d)
any order, direction or other requirement given or made by an authority;
(e)
an order made under Division 9.3, 9.4 or 9.5 of the Environmental
Planning and Assessment Act 1979; and
The Common Seal of the Owners - Strata Plan No. 105121 was affixed on
the 28 day of August 2025 in the presence of
Signature :.
Amy Robinson
-359920ADE97E46F ...
Name :.
Amy Robinson
strata managing agent,
BEING THE PERSON AUTHORISED BY
SECTION 273 OF THE STRATA SCHEMES
MANAGEMENT ACT 2015 TO ATTEST
THE AFFIXING OF THE SEAL.

--- Chunk 1 ---
105121 was affixed on
the 28 day of August 2025 in the presence of
Signature :.
Amy Robinson
-359920ADE97E46F ...
Name :.
Amy Robinson
strata managing agent,
BEING THE PERSON AUTHORISED BY
SECTION 273 OF THE STRATA SCHEMES
MANAGEMENT ACT 2015 TO ATTEST
THE AFFIXING OF THE SEAL.
Electronic
signature of
me, Amy
Robinson
affixed by me
on 28
August 2025
Signed by:
STRATĄ
PLAN
Common
Seal
THE OWNERS
No. 10512
PAGE 2 OF 146
1

============================================================
PAGE 4
============================================================
(f)
an order made under Part 2 or Part 5 of Chapter 7 of the Local
Government Act 1993.
Approved Insulation is insulation for hard floors as approved by the executive
committee from time to time.
Approved Underlay Is underlay for carpeting as approved by the executive
committee from time to time.
authority means:
(a)
any Commonwealth, state or local government, semi-government,
statutory, public or other body or person (or body or person otherwise
authorised by law) having jurisdiction;
(b)
a consent authority or principal certifying authority within the meaning
of the Environmental Planning and Assessment Act 1979;
(c)
the council having the relevant regulatory functions under Chapter 7 of
the Local Government Act 1993; and
(d)
an authorised fire officer within the meaning of Schedule 5 clause 16 of
the Environmental Planning and Assessment Act 1979;
balcony means that part of a Lot which is noted as "B" on the Strata Plan
includes a terrace and courtyard.
BBQ Area means the BBQ area located on Common Property on Level 6 of
Vista Victoria Gladesville marked as "BBQ" on the Identification Plan (Sheet
99).
The Residential Lot Owners jointly have exclusive use of the BBQ Area. See
by-law 44 for more information.
Bicycle Parking Bays means the Common Property bicycle parking facilities
located on Common Property on Lower Ground Floor of Vista Victoria
Gladesville and marked as "BR" on the Identification Plan (Sheet 92). Use of
the Bicycle Parking Bays is regulated in by- law 46.
Page 3 of 146

============================================================
PAGE 5
============================================================
Bond means the greater of:
(a)
$1,000; and
(b)
10% of the cost of your Renovations or Building Works up to a maximum
of $10,000.
Building means the building(s) erected on the Parcel.
Building Maintenance Records means the records of all maintenance works
carried out In the Building.
Building Manager is the person the Owners Corporation appoints under by-
law 35 as the Building manager for Vista Victoria Gladesville who has the
Owners Corporation's authority to act on its behalf as Indicated in these by-
laws for the purposes of these by-laws.
Building Works are any works, alterations, additions, damage, removal,
repairs or replacement of:
(a)
Common Property structures, Including the Common Property walls,
floor and ceiling enclosing your Lot. Common Property walls Include
windows and doors in those walls;
(b)
Common Property services;
(c)
the internal walls inside your Lot (e.g. wall dividing two rooms In your
Lot);
(d)
the structure of your Lot;
(e)
your Lot; or
(f)
another Lot
and includes damaging, altering or removing or erecting a load bearing wall or
non-load bearing wall, works which affect the external appearance of a Lot or
Vista Victoria Gladesville (Including changes to external colours), temporary
Page 4 of 146

============================================================
PAGE 6
============================================================
shut-down of services required to carry out building works or alterations,
installation of blinds, security mechanisms, screens, signs and placards BUT
Building Works exclude minor works or alterations to the interior of Common
Property walls enclosing a Lot (e.g. hanging pictures or attaching items to those
walls).
by-laws are the by-laws under the Act in force for the Residential Lots,
Commercial Lots and Carspace Lots which form Vista Victoria Gladesville.
Carspace Lot means a utility Lot for parking motor vehicles which is associated
with a Residential Lot.
Checklist means a checklist of things you should do and steps you should take
when changing floor coverings, carrying out Renovations or carrying out
Building Work; such checklist being available from the Building Manager;
Cleaner is the person the Owners Corporation or Building Manager appoints
as the cleaner for Vista Victoria Gladesville.
Cleaner's Tollet means the toilet designated for use by the Cleaner.

In [30]:
sample_text = nodes[0].text
embedding = embed_model.get_text_embedding(sample_text)
print(f"Dimensions: {len(embedding)}")
print(f"First 10 values: {embedding[:10]}")

Dimensions: 384
First 10 values: [-0.03537818789482117, 0.027262406423687935, 0.029369348660111427, 0.02158583700656891, 0.03288840129971504, 0.0431324765086174, -0.006981388665735722, 0.023205827921628952, -0.04022587463259697, 0.02643793635070324]

In [33]:
import numpy as np

vector_data = basic_index.vector_store._data
node_ids = list(vector_data.embedding_dict.keys())
print(f"Vectors stored: {len(node_ids)}")
first_vec = vector_data.embedding_dict[node_ids[0]]
print(f"Vector length: {len(first_vec)}")
print(f"First 10 values: {first_vec[:10]}")


def cosine_similarity(a, b):
    a, b = np.array(a), np.array(b)
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

vec0 = vector_data.embedding_dict[node_ids[0]]
vec1 = vector_data.embedding_dict[node_ids[1]]
vec2 = vector_data.embedding_dict[node_ids[2]]

print(f"Chunk 0 vs Chunk 1: {cosine_similarity(vec0, vec1):.4f}")
print(f"Chunk 0 vs Chunk 2: {cosine_similarity(vec0, vec2):.4f}")
print(f"\nChunk 0 text: {nodes[0].text[:100]}")
print(f"Chunk 1 text: {nodes[1].text[:100]}")
print(f"Chunk 2 text: {nodes[2].text[:100]}")

Vectors stored: 40
Vector length: 384
First 10 values: [-0.03537818789482117, 0.027262406423687935, 0.029369348660111427, 0.02158583700656891, 0.03288840129971504, 0.0431324765086174, -0.006981388665735722, 0.023205827921628952, -0.04022587463259697, 0.02643793635070324]
Chunk 0 vs Chunk 1: 0.8074
Chunk 0 vs Chunk 2: 0.7559

Chunk 0 text: ============================================================
PAGE 1
==============================
Chunk 1 text: 105121 was affixed on
the 28 day of August 2025 in the presence of
Signature :.
Amy Robinson
-35
Chunk 2 text: hanging pictures or attaching items to those
walls).
by-laws are the by-laws under the Act in forc

In [35]:
# Auto-merging leaf nodes — should be much shorter
from llama_index.core.node_parser import get_leaf_nodes
am_nodes = list(automerging_index.docstore.docs.values())
leaf_nodes = [n for n in am_nodes if n.metadata.get("is_leaf", True)]
print(nodes[0].text[:300])         # basic chunk
print("---")
print(am_nodes[0].text[:300])      # auto-merging chunk

============================================================
PAGE 1
============================================================
Strata Plan 105121
Vista Victoria
312 Victoria Road
GLADESVILLE NSW 2111
Registered By-Laws

============================================================
PAGE 2
---
============================================================
PAGE 1
============================================================
Strata Plan 105121
Vista Victoria
312 Victoria Road
GLADESVILLE NSW 2111
Registered By-Laws

============================================================
PAGE 2

In [36]:
for i in range(3, 8):
    print(f"\n--- AM node {i} ({len(am_nodes[i].text)} chars) ---")
    print(am_nodes[i].text[:300])
    print(f"\n--- Basic node {i} ({len(nodes[i].text)} chars) ---")
    print(nodes[i].text[:300])
    print("="*60)

--- AM node 3 (9489 chars) ---
6.2
You must
(a)
comply with the Guidelines;
(b)
ensure that all floor space and surrounding areas within your Lot are
covered or otherwise treated in accordance with the Guidelines to
reduce appropriately and suitably noise transmission that might
Page 18 of 146

=========================

--- Basic node 3 (4123 chars) ---
Lot means a lot in the Strata Plan, being a Residential Lot, Commercial Lot or
Carspace Lot in Vista Victoria Gladesvilie and any Lots into which they are
subdivided or resubdivided.
O&M Manual means the operations and maintenance and manual for the
Building (as amended from time to time).
Occu
============================================================

--- AM node 4 (9820 chars) ---
8.4
If you are an Owner, you must not carry out Building Work unless first you:
(a)
obtain a Checklist from the Building Manager;
(b)
submit plans detailing the proposed Building Work (including details of
tradespersons and contractors, materials, style, design, colour
schemes and any other d

--- Basic node 4 (4771 chars) ---
Signage Equipment means pipes, wires, cables, ducts, electrical conduits,
electrical meters and other electrical equipment in or on the Common Property
which service the Signs.
Signs means illuminated or other signs displaying a business name, logo,
advertisement or a combination of them.
Strat
============================================================

--- AM node 5 (9592 chars) ---
otherwise impede drainage associated with the balcony and Building.
(b)
any bicycle, tricycle or similar equipment or parts of such equipment;
(c)
any mirrors, artworks, colourful (non-white/cream) or reflective surfaces
either free standing or mounted to any exterior surface;
(d)
any claddin

--- Basic node 5 (4704 chars) ---
Occupiers may exercise rights
2.7
You may allow another Owner or an Occupier to exercise your rights under a
Common Property Rights By-Law, However, you remain responsible to the
Owners Corporation and, where appropriate, Government Agencies to comply
with your obligations under the Common Prop
============================================================

--- AM node 6 (9542 chars) ---
"Call-out" means the activation of smoke or fire alarms forming fire safety
equipment resulting in the attendance of an authorised contractor or
Government Agency to investigate the cause and any consequential
attendance by Ryde City Council to investigate the fire safety of Vista Victoria
Glade

--- Basic node 6 (4053 chars) ---
3.3
Subject to the by-laws, you must not allow children in your care or visiting you
at Vista Victoria Gladesville to:
(a)
play on Common Property inside Vista Victoria Gladesville (e.g.
hallways or stairs); or
(b)
unless an adult exercising effective control is with them, be in an area
of C
============================================================

--- AM node 7 (10194 chars) ---
22A.2 The Residential Lot Owners jointly have:
(a)
exclusive use of the Residential Garbage Room and Residential
Garbage Chutes;
(b)
a special privilege to place and store garbage and recyclable materials
In the Residential Garbage Room according to this by- law; and
(c)
a special privilege

--- Basic node 7 (5156 chars) ---
Window coverings
5.3
Window coverings (e.g. curtains, blinds) in your Lot must have a white backing
and otherwise be of a colour and design approved by the Owners Corporation
as in keeping with the design and appearance of Vista Victoria Gladesville
when viewed from outside.
6
Floor coverings
============================================================

In [ ]:
q = "What are the rules about floor coverings?"

for name, engine in [("Basic", basic_engine), ("Sentence Window", sw_engine), ("Auto-merging", am_engine)]:
    response = engine.query(q)
    print(f"\n{'='*40}")
    print(f"{name} answer:")
    print(str(response))

In [ ]:

q = "What are all my obligations as a lot owner regarding common property?"

#basic_engine.query(q).response

#sw_engine.query(q).response

am_engine.query(q).response

"# Lot Owner Obligations Regarding Common Property\n\nAs a lot owner, you have the following obligations regarding common property:\n\n**Access and Maintenance:**\n- You must give the Owners Corporation (or persons authorized by it) access to your lot according to notice provided, at your own cost\n- You must pay the Owners Corporation for its costs in doing work on your lot\n- You may be required to provide access to storage spaces within your lot for inspecting, testing, and maintaining services and infrastructure located within the common property (with prior notice, except in emergencies)\n\n**Damage and Hazards:**\n- You must not do anything or permit any authorized person to do anything on your lot or common property that is likely to create a hazard or danger to other lot owners, occupiers, or persons lawfully using the common property\n- If you or an authorized person causes damage to common property while using it, you must promptly notify the Owners Corporation and compensate them accordingly\n- If your proposed works interfere with or damage common property or other lots' property, you must rectify that interference or damage within a reasonable period of time\n\n**Cleanliness and Storage:**\n- You must keep all affected areas of common property outside your lot clean and tidy, removing all debris\n- You must not store materials, goods, or machinery between the building line and street alignment\n\n**Modifications:**\n- You must not vary any proposed works without first obtaining written consent from the Owners Corporation"

In [51]:
import textwrap

q = "What is the full process for getting approval to renovate my apartment?"

for name, engine in [("Basic", basic_engine), ("Sentence Window", sw_engine), ("Auto-merging", am_engine)]:
    print(f"\n{'='*60}")
    print(f"{name}")
    print('='*60)
    print(textwrap.fill(engine.query(q).response, width=80))

============================================================
Basic
============================================================
# Process for Getting Approval to Renovate Your Apartment  To obtain approval
for renovations to your apartment, you must follow these steps:  ## Before
Starting Work  1. **Obtain a Checklist** from the Building Manager  2. **Secure
Necessary Consents**    - Get approval from the Owners Corporation    - Obtain
consents from all relevant Government Agencies    - Provide written evidence of
all Government Agency consents to the executive committee  3. **Locate Service
Lines and Pipes**    - Find out where all service lines and pipes are located
before commencing work  4. **Notify the Building Manager**    - Provide 14 days'
written notice describing the proposed work in detail  5. **Arrange Work
Details** (if the executive committee deems it necessary)    - Agree on a
suitable time and means of access to the building    - Confirm work hours, work
methods, and debris disposal arrangements    - Designate a supervisor who will
be responsible for the work and available in emergencies    - Deliver the Bond
to the Building Manager  ## During the Work  - Use qualified, reputable,
licensed, and insured contractors - Perform work properly to the Owners
Corporation's and Government Agencies' reasonable satisfaction - Protect service
lines and pipes - Avoid damaging fire-rated doors or walls - Immediately repair
any damage caused to Common Property or other lots  ## After Completion  - If
requested by the Owners Corporation, provide written certification that the work
meets relevant Australian Building, engineering, fire, and/or acoustic standards
and hasn't compromised the building's structural integrity

============================================================
Sentence Window
============================================================
# Process for Getting Approval to Renovate Your Apartment  To obtain approval
for renovations to your apartment, you must follow these steps:  ## Before
Starting Work  1. **Obtain a Checklist** from the Building Manager  2. **Secure
Necessary Consents**    - Get approval from the Owners Corporation    - Obtain
consents from all relevant Government Agencies    - Provide written evidence of
all Government Agency consents to the executive committee  3. **Locate Service
Lines and Pipes**    - Find out where all service lines and pipes are located
4. **Provide Notice**    - Give the Building Manager 14 days' written notice
describing the proposed work in detail  5. **Arrange Additional Requirements**
(if the executive committee deems necessary)    - Arrange a suitable time and
means to access the building    - Agree on work hours, work methods, and debris
disposal    - Designate a nominee responsible for supervising the work and
available for emergencies    - Deliver a Bond to the Building Manager  ## During
the Work  - Use qualified, reputable, licensed, and insured contractors - Comply
with all agreed arrangements and the Building Manager's reasonable requirements
- Protect service lines and pipes - Perform work to the Owners Corporation's and
Government Agencies' reasonable satisfaction - Immediately repair any damage
caused - Avoid damaging fire-rated doors or walls  ## After Completion  - If
requested by the Owners Corporation, provide written certification that the work
meets relevant Australian Building, engineering, fire, and/or acoustic standards
and hasn't compromised the building's structural integrity

============================================================
Auto-merging
============================================================
# Process for Getting Approval to Renovate Your Apartment  To undertake
renovations, you must complete the following steps before commencing any work:
1. **Obtain a Checklist** from the Building Manager  2. **Secure Necessary
Consents**    - Obtain approval from the Owners Corporation    - Obtain consents
from all relevant Government Agencies    - Provide written evidence of all
Government Agency consents to the executive committee  3. **Locate Service Lines
and Pipes**    - Find out where service lines and pipes are located in your
apartment  4. **Provide Written Notice**    - Give the Building Manager 14 days'
written notice that describes in detail what work is proposed  5. **Submit
Bond** (if required)    - Deliver the Bond to the Building Manager when deemed
necessary by the executive committee  ## During Renovations  Once approved, you
must: - Comply with all arrangements from the approval process - Use only
qualified, reputable, licensed, and insured contractors - Ensure contractors
also comply with all requirements - Not damage service lines or pipes or
interrupt services to the building  Following these steps ensures your
renovation work meets all building requirements and protections.